receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://localhost:8080"

exporters:
  otlphttp/elastic:
    endpoint: "${ELASTIC_APM_SERVER_URL}"
    compression: none
    headers:
      Authorization: "Bearer ${ELASTIC_APM_SECRET_TOKEN}"
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/elastic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/elastic]
